######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 13 14:59:37 2008
######################################################################

CONFIG = console
TEMPLATE = app
TARGET = testlu
DEPENDPATH += .
INCLUDEPATH += . ../../LibLA/include ../../LibStructural/include
win32:LIBS += -L../../bin -lLibLA
win32:DEFINES += LIB_EXPORTS WIN32
unix:LIBS += -L../../lib -lLibStructural
mac:LIBS += -L../../lib -lLibStructural

# Input
SOURCES += testlu.c
