######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 13 14:59:37 2008
######################################################################

CONFIG = console
TEMPLATE = app
TARGET = fluxbalance
DEPENDPATH += .
INCLUDEPATH += . ../../LibLA/include ../../LibStructural/include ../../LibStructural/
LIBS += -L../../lib -lLibStructural

# Input
SOURCES += fluxbalance.cpp
