######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 12 00:15:35 2008
######################################################################

SBW_DIR = /Users/fbergmann/Development/core

CONFIG = console
TEMPLATE = app
TARGET = TestLibStruct
DEPENDPATH += . include
INCLUDEPATH += . ../LibStructural/include ../LibLA/include

LIBS += -L../build/ -lLibLA -L$$SBW_DIR/lib  -lLibStructural
unix:LIBS += -L../bin -llpsolve55
mac:LIBS += -L../bin -llpsolve55
win32:LIBS += -L../bin -lliblpsolve55
win32:LIBS += -L../LibStructural/lib 

include(../common.pri)

# Input
SOURCES += program.cpp
