######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 11 23:30:49 2008
######################################################################

include(../common.pri)

TEMPLATE = lib
TARGET = LibLA-static
DEPENDPATH += . include
INCLUDEPATH += . include
CONFIG -= qt 
CONFIG -= shared
CONFIG += static

CONFIG(debug, debug|release) {
     win32: TARGET = $$join(TARGET,,,d)
}


# Input
HEADERS += ../include/blaswrap.h \
           ../include/clapack.h \
           ../include/complex.h \
           ../include/f2c.h \
           ../include/libla.h \
           ../include/libutil.h \
           ../include/matrix.h \
           ../include/util.h

SOURCES += ../LibLA/complex.cpp \
					 ../LibLA/libla.cpp \
					 ../LibLA/matrix.cpp \
					 ../LibLA/util.cpp
