######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 11 23:30:49 2008
######################################################################

include(../common.pri)

TEMPLATE = lib
TARGET = LibLA
DEPENDPATH += . include
INCLUDEPATH += . include
CONFIG -= qt 

CONFIG(debug, debug|release) {
     win32: TARGET = $$join(TARGET,,,d)
}

# Input
HEADERS += ../include/blaswrap.h \
           ../include/clapack.h \
           ../include/complex.h \
           ../include/f2c.h \
           ../include/libla.h \
           ../include/libutil.h \
           ../include/matrix.h \
           ../include/util.h

SOURCES += complex.cpp \
					 libla.cpp \
					 matrix.cpp \
					 util.cpp
